"use strict";

const dialog = document.querySelector("#auth-dialog");
const form = document.querySelector("#auth-form");
const formWrap = document.querySelector(".auth-form-wrap");
const authTitle = document.querySelector("#auth-title");
const authKicker = document.querySelector("#auth-kicker");
const switchAuth = document.querySelector("#switch-auth");
const switchCopy = document.querySelector("#switch-copy");
const formMessage = document.querySelector(".form-message");
let authMode = "login";
let currentDashboard = null;

function setAuthMode(mode) { const signup=mode==="signup";authMode=mode;formWrap.classList.toggle("sign-up",signup);authKicker.textContent=signup?"OPEN YOUR ACCOUNT":"WELCOME BACK";authTitle.textContent=signup?"A smarter way to bank.":"Sign in to your account";form.elements.password.autocomplete=signup?"new-password":"current-password";form.elements.name.required=signup;switchCopy.textContent=signup?"Already a customer?":"New to CYBERBADFIT Bank?";switchAuth.textContent=signup?"Sign in":"Create an account";formMessage.textContent="";formMessage.classList.remove("error"); }
function openAuth(mode) { setAuthMode(mode);dialog.showModal();document.querySelector("input[name='email']").focus(); }
document.querySelectorAll("[data-open-auth]").forEach(button=>button.addEventListener("click",()=>openAuth(button.dataset.openAuth)));
document.querySelector(".dialog-close").addEventListener("click",()=>dialog.close());switchAuth.addEventListener("click",()=>setAuthMode(authMode==="login"?"signup":"login"));
async function api(path,options={}) { const token=sessionStorage.getItem("cyberbadfit.session");const headers={"Content-Type":"application/json",...(options.headers||{})};if(token)headers.Authorization=`Bearer ${token}`;const response=await fetch(path,{...options,headers});const result=response.status===204?{}:await response.json();if(!response.ok)throw new Error(result.error||"Something went wrong.");return result; }
form.addEventListener("submit",async event=>{event.preventDefault();const submit=form.querySelector("button[type='submit']"),payload=Object.fromEntries(new FormData(form));submit.disabled=true;formMessage.textContent="Securing your request...";formMessage.classList.remove("error");try{const result=await api(authMode==="signup"?"/api/signup":"/api/login",{method:"POST",body:JSON.stringify(payload)});sessionStorage.setItem("cyberbadfit.session",result.token);formMessage.textContent="Success. Opening your secure workspace...";await loadDashboard();setTimeout(()=>dialog.close(),280);}catch(error){formMessage.textContent=error.message;formMessage.classList.add("error");}finally{submit.disabled=false;}});
function currency(value) { return new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(value||0).replace("₹","Rs. "); }
function setText(selector,value) { const target=document.querySelector(selector);if(target)target.textContent=value; }
function transactionIcon(category) { return category==="Income"||category==="Deposit"||category==="Loan"?"+":category==="Utilities"?"~":category==="Transfer"?"->":category==="ATM"?"$":"o"; }
function renderTransactions(items) { const list=document.querySelector("#transaction-list");list.replaceChildren();items.forEach(item=>{const row=document.createElement("article"),icon=document.createElement("span"),details=document.createElement("div"),merchant=document.createElement("b"),meta=document.createElement("small"),amount=document.createElement("span");row.className="transaction-row";icon.className="transaction-icon";icon.textContent=transactionIcon(item.category);merchant.textContent=item.merchant;meta.textContent=`${item.category} · ${item.date}`;details.append(merchant,meta);amount.className=`transaction-amount ${item.amount>0?"positive":""}`;amount.textContent=`${item.amount>0?"+ ":"- "}${currency(Math.abs(item.amount))}`;row.append(icon,details,amount);list.append(row);});if(!items.length)list.textContent="No records to display."; }
function ensureServices() { let section=document.querySelector("#service-section");if(section)return section;section=document.createElement("section");section.id="service-section";section.className="service-section";document.querySelector(".dash-main").append(section);return section; }
const serviceForms={
  deposit:{title:"Deposit funds",fields:["amount"]},withdraw:{title:"Withdraw funds",fields:["amount"]},atm:{title:"ATM withdrawal",fields:["amount"]},transfer:{title:"Transfer funds",fields:["recipient","amount"]},loan:{title:"Apply for loan",fields:["amount","months"]},fd:{title:"Open fixed deposit",fields:["amount","months"]},card:{title:"Request debit card",fields:[]},cheque:{title:"Request cheque book",fields:["leaves"]},
  "create-customer":{title:"Register customer",fields:["name","email","mobile","password"]},"open-account":{title:"Open customer account",fields:["email","accountType","amount"]},"add-employee":{title:"Add employee",fields:["name","email","designation","password"]},"add-branch":{title:"Add branch",fields:["name","city","ifsc"]},backup:{title:"Create backup",fields:[]},restore:{title:"Restore backup",fields:[]}
};
const serviceActions={Deposit:"deposit",Withdraw:"withdraw",Transfer:"transfer","Apply loan":"loan","Open fixed deposit":"fd","Request card":"card","Cheque book":"cheque",ATM:"atm","Register customer":"create-customer","Open account":"open-account","Employee management":"add-employee","Branch management":"add-branch",Backup:"backup",Restore:"restore"};
function field(label) { const type=label==="password"?"password":label==="email"?"email":label==="amount"||label==="months"||label==="leaves"?"number":"text";const pretty={name:"Full name",email:"Email address",mobile:"Mobile number",password:"Temporary password (12+ characters)",amount:"Amount (Rs.)",months:"Term (months)",leaves:"Cheque leaves",recipient:"Recipient",designation:"Designation",city:"City",ifsc:"IFSC",accountType:"Account type"}[label]||label;return label==="accountType"?`<label>${pretty}<select name="accountType"><option>Savings</option><option>Current</option></select></label>`:`<label>${pretty}<input name="${label}" type="${type}" ${label==="amount"?"min=\"1\" step=\"0.01\"":label==="months"?"min=\"1\" max=\"360\"":label==="leaves"?"min=\"10\" max=\"100\"":""} required></label>`; }
function openService(type) { const config=serviceForms[type];if(!config)return;let modal=document.querySelector("#service-modal");if(!modal){modal=document.createElement("dialog");modal.id="service-modal";modal.className="service-modal";document.body.append(modal);}modal.innerHTML=`<button class="dialog-close" aria-label="Close">&times;</button><p class="eyebrow">SECURE SERVICE</p><h2>${config.title}</h2><form>${config.fields.map(field).join("")}<button class="button" type="submit">Confirm request <span>-></span></button><p class="form-message" role="status"></p></form>`;modal.querySelector(".dialog-close").onclick=()=>modal.close();modal.querySelector("form").onsubmit=async event=>{event.preventDefault();const message=modal.querySelector(".form-message"),payload=Object.fromEntries(new FormData(event.currentTarget));try{const result=await api("/api/action",{method:"POST",body:JSON.stringify({...payload,type})});message.textContent=result.message;message.classList.remove("error");await loadDashboard();}catch(error){message.textContent=error.message;message.classList.add("error");}};modal.showModal(); }
async function showRecords(kind) { const section=ensureServices();section.innerHTML=`<div class="service-heading"><div><p class="eyebrow">ADMINISTRATIVE RECORDS</p><h3>${kind}</h3></div><button class="text-button" id="back-services">Back to services</button></div><div class="record-table" id="record-table">Loading records...</div>`;document.querySelector("#back-services").onclick=()=>renderServices(currentDashboard);try{const {items}=await api(`/api/records?kind=${encodeURIComponent(kind)}`);const table=section.querySelector("#record-table");table.replaceChildren();if(!items.length){table.textContent="No records found.";return;}const columns=Object.keys(items[0]).filter(key=>!key.toLowerCase().includes("hash")&&!key.toLowerCase().includes("salt")).slice(0,6);const header=document.createElement("div");header.className="record-row record-header";columns.forEach(key=>{const cell=document.createElement("b");cell.textContent=key;header.append(cell);});table.append(header);items.slice(0,20).forEach(item=>{const row=document.createElement("div");row.className="record-row";columns.forEach(key=>{const cell=document.createElement("span");cell.textContent=typeof item[key]==="object"?JSON.stringify(item[key]):String(item[key]);row.append(cell);});table.append(row);});}catch(error){section.querySelector("#record-table").textContent=error.message;} }
function renderServices(data) { const section=ensureServices();const staff=data.role!=="customer";const records=data.role==="admin"?["customers","employees","branches","accounts","transactions","loans","fixedDeposits","cards","cheques","logs"]:["customers","accounts","transactions","loans","cheques"];const buttons=data.services.map(label=>{const action=serviceActions[label];if(action)return `<button class="service-card" data-service="${action}"><span>${label.slice(0,1)}</span><b>${label}</b><small>Open secure workflow -></small></button>`;if(label==="Loan approvals"||label==="Cheque approvals")return `<button class="service-card" data-process="${label.includes("Loan")?"loan":"cheque"}"><span>+</span><b>${label}</b><small>Review pending requests -></small></button>`;if(label==="Reports")return `<button class="service-card" data-record="transactions"><span>R</span><b>Reports & analytics</b><small>View transaction records -></small></button>`;if(label==="Customer search"||label==="Customer management")return `<button class="service-card" data-record="customers"><span>C</span><b>${label}</b><small>View protected records -></small></button>`;if(label==="Account controls")return `<button class="service-card" data-record="accounts"><span>A</span><b>Account controls</b><small>View account records -></small></button>`;return "";}).join("");section.innerHTML=`<div class="service-heading"><div><p class="eyebrow">${staff?"STAFF CONTROL CENTRE":"DIGITAL BANKING SERVICES"}</p><h3>${staff?"Manage your bank operations":"Choose a secure service"}</h3></div><span>${data.services.length} workflows available</span></div><div class="service-grid">${buttons}</div>${staff?`<div class="pending-grid"><div><b>Pending loans</b><div id="loan-queue"></div></div><div><b>Pending cheques</b><div id="cheque-queue"></div></div></div><div class="record-links">${records.map(kind=>`<button data-record="${kind}">${kind}</button>`).join("")}</div>`:""}`;section.querySelectorAll("[data-service]").forEach(button=>button.onclick=()=>openService(button.dataset.service));section.querySelectorAll("[data-record]").forEach(button=>button.onclick=()=>showRecords(button.dataset.record));section.querySelectorAll("[data-process]").forEach(button=>{const kind=button.dataset.process;const item=(kind==="loan"?data.loans:data.cheques)[0];if(!item)return;openProcess(kind,item);});if(staff){renderQueue("#loan-queue",data.loans,"loan");renderQueue("#cheque-queue",data.cheques,"cheque");} }
function renderQueue(selector,items,kind){const target=document.querySelector(selector);if(!target)return;target.replaceChildren();if(!items.length){target.textContent="No pending requests.";return;}items.forEach(item=>{const box=document.createElement("div");box.className="queue-item";box.innerHTML=`<span>${item.id}</span><b>${kind==="loan"?currency(item.amount):`${item.leaves} leaves`}</b><button>Review</button>`;box.querySelector("button").onclick=()=>openProcess(kind,item);target.append(box);});}
function openProcess(kind,item){const modal=document.querySelector("#service-modal")||document.createElement("dialog");if(!modal.id){modal.id="service-modal";modal.className="service-modal";document.body.append(modal);}modal.innerHTML=`<button class="dialog-close">&times;</button><p class="eyebrow">STAFF APPROVAL</p><h2>${kind==="loan"?"Loan application":"Cheque-book request"}</h2><p>${item.id} · ${kind==="loan"?currency(item.amount):`${item.leaves} leaves`}</p><div class="decision-row"><button class="button" data-decision="approve">Approve</button><button class="danger-button" data-decision="reject">Reject</button></div><p class="form-message"></p>`;modal.querySelector(".dialog-close").onclick=()=>modal.close();modal.querySelectorAll("[data-decision]").forEach(button=>button.onclick=async()=>{try{const result=await api("/api/action",{method:"POST",body:JSON.stringify({type:`process-${kind}`,id:item.id,decision:button.dataset.decision})});modal.querySelector(".form-message").textContent=result.message;await loadDashboard();}catch(error){modal.querySelector(".form-message").textContent=error.message;modal.querySelector(".form-message").classList.add("error");}});modal.showModal();}
function renderCustomer(data){setText(".dash-balance p","AVAILABLE BALANCE");setText("#account-balance",currency(data.account?.available));setText("#account-type",data.account?.type||"Account pending activation");setText("#account-number",data.account?.number||"No account");setText(".spending-card p","MONTHLY SPEND");setText("#spending-value",currency(data.spending?.used));const percent=Math.min(100,Math.round((data.spending?.used||0)/(data.spending?.limit||1)*100));document.querySelector("#spending-progress").style.width=`${percent}%`;setText("#spending-caption",`${percent}% of your Rs. ${(data.spending?.limit||0).toLocaleString("en-IN")} limit`);setText(".rewards-card p","REWARDS BALANCE");setText("#reward-points",(data.account?.rewards||0).toLocaleString("en-IN"));renderTransactions(data.transactions);}
function renderStaff(data){const m=data.metrics;setText(".dash-balance p","TOTAL CUSTOMERS");setText("#account-balance",String(m.customers));setText("#account-type",`${m.accounts} accounts active`);setText("#account-number",`Rs. ${m.totalBalance.toLocaleString("en-IN")} deposits`);setText(".spending-card p","TEAM MEMBERS");setText("#spending-value",String(m.employees));document.querySelector("#spending-progress").style.width=`${Math.min(100,m.accounts*12)}%`;setText("#spending-caption",`${m.transactions} recorded transactions`);setText(".rewards-card p","PENDING LOANS");setText("#reward-points",String(m.pendingLoans));renderTransactions(data.transactions);}
function renderDashboard(data){currentDashboard=data;setText("#dashboard-name",data.user.name.split(" ")[0]);setText(".dash-header .eyebrow",data.role==="customer"?"PERSONAL OVERVIEW":data.role==="admin"?"ADMINISTRATOR DASHBOARD":"EMPLOYEE WORKSPACE");setText(".dash-header h2",data.role==="customer"?`Good morning, ${data.user.name.split(" ")[0]}.`:data.role==="admin"?"Bank operations overview.":"Customer service workspace.");data.role==="customer"?renderCustomer(data):renderStaff(data);renderServices(data);document.querySelector("#dashboard").hidden=false;document.body.style.overflow="hidden";}
async function loadDashboard(){try{renderDashboard(await api("/api/dashboard"));}catch{sessionStorage.removeItem("cyberbadfit.session");}}
document.querySelector("#logout-button").addEventListener("click",async()=>{try{await api("/api/logout",{method:"POST"});}catch{}sessionStorage.removeItem("cyberbadfit.session");document.querySelector("#dashboard").hidden=true;document.body.style.overflow="";currentDashboard=null;});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("visible");observer.unobserve(entry.target);}}),{threshold:.14});document.querySelectorAll(".reveal").forEach(element=>observer.observe(element));if(sessionStorage.getItem("cyberbadfit.session"))loadDashboard();
